---
language: node_js
node_js:
  - "8"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    - secure: EYaa9XxKkfJbQENuQPNFAIIieMWBiSknGCO9he8MH8ZHbqJODTjFixJnD5ZYLZCXH67SmjorBneznQHp8Xaf0aIuHbRhRY/MOUzqEWw12MmexW1kJF5wX+oxEnvzoiVAUJLNTIQi+g5WN43YBleASKMjUPa2i/3GBIcTlsVdf3U=
    - secure: g+Qh9jUTpK1yFpcZi9O8rsybfqv3TFE2hTFvG8XZ+QaQYBLLZ52JfhsJhdI0cvRRp7qWOhzE784iadkPWgvhj8c0/N/af5ZrSP3ceiv6RKqSUG2/iQyzX/qUh3vqrZ7a4xTsELTwswQtR+sA+I+DQVVlnqcCqYTAW2SFR/D4H8o=

jobs:
  fail_fast: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary

  include:
    # runs tests with current locked deps and linting
    - stage: test
      script:
        - yarn lint:hbs
        - yarn lint:js
        - yarn test

    # runs tests for ember_debug against each supported Ember version
    - stage: ember debug test
      env: EMBER_TRY_SCENARIO=ember-lts-3.4
    - env: EMBER_TRY_SCENARIO=ember-lts-3.8
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-default

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - travis_retry yarn install --ignore-engines

script:
  - travis_retry node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --- node_modules/.bin/ember test --filter="Ember Debug"

before_deploy:
  - yarn run build:production

deploy:
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  provider: s3
  bucket: "ember-extension"
  acl: public_read
  cache_control: "max-age=86400000, public"
  skip_cleanup: true
  local_dir: dist/bookmarklet
  upload-dir: dist_bookmarklet
  on:
    branch: stable

branches:
  only:
    - "master"
    - "stable"
    - "ember-0.0.0-2.7.0"
    - "ember-2.7.0-3.4.0"
